
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xc7\x8dP%l\x1eR\xdb1\xd5@-6\xb6\xde\x17'
    
_lr_action_items = {'BE':([3,],[4,]),'DIGIT':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[13,-7,-11,-8,-12,-10,13,-9,13,13,13,-6,13,13,-3,-4,-5,]),'REPEAT':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[6,-7,-11,-8,-12,-10,6,-9,6,6,6,-6,6,6,-3,-4,-5,]),'WORD':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[7,-7,-11,-8,-12,-10,7,-9,7,7,7,-6,7,7,-3,-4,-5,]),'NAME':([1,4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[3,8,-7,-11,-8,-12,-10,8,-9,8,8,8,-6,8,8,-3,-4,-5,]),'NUMBER':([6,],[16,]),'CHAR':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[11,-7,-11,-8,-12,-10,11,-9,11,11,11,-6,11,11,-3,-4,-5,]),'LET':([0,],[1,]),'NOT':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[12,-7,-11,-8,-12,-10,12,-9,12,12,12,-6,12,12,-3,-4,-5,]),'CONST':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[10,-7,-11,-8,-12,-10,10,-9,10,10,10,-6,10,10,-3,-4,-5,]),'OR':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[14,-7,-11,-8,-12,-10,14,-9,14,14,14,-6,14,14,-3,-4,-5,]),'CONCAT':([4,5,7,8,10,11,12,13,14,15,16,17,18,19,20,21,22,],[15,-7,-11,-8,-12,-10,15,-9,15,15,15,-6,15,15,-3,-4,-5,]),'$end':([2,5,7,8,9,10,11,13,17,20,21,22,],[0,-7,-11,-8,-1,-12,-10,-9,-6,-3,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([4,12,14,15,16,18,19,],[9,17,18,19,20,21,22,]),'term':([4,12,14,15,16,18,19,],[5,5,5,5,5,5,5,]),'assign':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> LET NAME BE expr','assign',4,'p_assign','/Users/bambool/Desktop/let/myyacc.py',8),
  ('show -> PRINT expr','show',2,'p_print','/Users/bambool/Desktop/let/myyacc.py',12),
  ('expr -> REPEAT NUMBER expr','expr',3,'p_expr_repeat','/Users/bambool/Desktop/let/myyacc.py',26),
  ('expr -> OR expr expr','expr',3,'p_expr_or','/Users/bambool/Desktop/let/myyacc.py',30),
  ('expr -> CONCAT expr expr','expr',3,'p_expr_concat','/Users/bambool/Desktop/let/myyacc.py',34),
  ('expr -> NOT expr','expr',2,'p_expr_not','/Users/bambool/Desktop/let/myyacc.py',38),
  ('expr -> term','expr',1,'p_expr_term','/Users/bambool/Desktop/let/myyacc.py',42),
  ('term -> NAME','term',1,'p_term_name','/Users/bambool/Desktop/let/myyacc.py',59),
  ('term -> DIGIT','term',1,'p_term_digit','/Users/bambool/Desktop/let/myyacc.py',66),
  ('term -> CHAR','term',1,'p_term_char','/Users/bambool/Desktop/let/myyacc.py',70),
  ('term -> WORD','term',1,'p_term_word','/Users/bambool/Desktop/let/myyacc.py',74),
  ('term -> CONST','term',1,'p_term_CONST','/Users/bambool/Desktop/let/myyacc.py',78),
]
